const XLSX = require('xlsx');
const fs = require('fs');
const path = require('path');

const INPUT_FILE = 'scholarship.xlsx';
const OUTPUT_FILE = 'supabase/migrations/seed_scholarships.sql';

function escapeSql(str) {
    if (str === null || str === undefined) return 'NULL';
    return "'" + String(str).replace(/'/g, "''").replace(/\n/g, "\\n") + "'";
}

function parseDate(value) {
    if (!value) return 'NULL';
    // If it's a number (Excel date), convert it
    if (typeof value === 'number') {
        const date = XLSX.SSF.parse_date_code(value);
        return `'${date.y}-${String(date.m).padStart(2, '0')}-${String(date.d).padStart(2, '0')}'`;
    }
    // If string, try to parse or return as is if YYYY-MM-DD
    const str = String(value).trim();
    if (str.match(/^\d{4}-\d{2}-\d{2}$/)) return `'${str}'`;
    // Fallback or handle other formats if needed
    return 'NULL';
}

function mapCategory(value) {
    if (!value) return "'private'";
    const str = String(value);
    if (str.includes('공공') || str.includes('지자체')) return "'public'";
    if (str.includes('교내') || str.includes('대학')) return "'university'";
    return "'private'";
}

function mapEnrollment(value) {
    if (!value) return "'enrolled,leave,expected'"; // Default broad
    const str = String(value);
    if (str.includes('졸업')) return "'graduated'";
    return "'enrolled,leave,expected'";
}

function run() {
    const workbook = XLSX.readFile(INPUT_FILE);
    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];

    // Read with header: 1 to get array of arrays, skip first row (title)
    const rows = XLSX.utils.sheet_to_json(sheet, { header: 1 });

    // Headers are in row index 1 (0-based)
    const headers = rows[1];
    const dataRows = rows.slice(2); // Data starts from row index 2

    // Map header names to indices
    const colMap = {};
    headers.forEach((h, i) => {
        if (h) colMap[h] = i;
    });

    let sql = `-- Generated by convert_excel_to_sql.js\n`;
    sql += `TRUNCATE TABLE scholarships;\n\n`;

    dataRows.forEach(row => {
        if (!row[colMap['장학 제목']]) return; // Skip empty rows

        const name = escapeSql(row[colMap['장학 제목']]);
        const foundation = escapeSql(row[colMap['후원 기관']]);

        // Category
        const categoryRaw = row[colMap['장학 종류']];
        const category = mapCategory(categoryRaw);

        // Amount & Support Details
        // User added specific columns: '금액' (Short) and '상세내용' (Long)
        // Fallback to '지원 금액' if they are missing
        const amountShortRaw = row[colMap['금액']];
        const amountLongRaw = row[colMap['상세내용']];
        const originalAmountRaw = row[colMap['지원 금액']];

        let amount = escapeSql(amountShortRaw || originalAmountRaw);
        // If using original and it's long, truncate it for the card
        if (!amountShortRaw && originalAmountRaw && String(originalAmountRaw).length > 20) {
            let summary = String(originalAmountRaw).split('\n')[0];
            if (summary.length > 15) summary = summary.substring(0, 15) + '...';
            amount = escapeSql(summary);
        }

        // support_details should be the long version
        const support_details = escapeSql(amountLongRaw || originalAmountRaw);

        const benefit_type = escapeSql(row[colMap['혜택 유형']]);
        const payment_method = escapeSql(row[colMap['지급 방식']]);
        const payment_period = escapeSql(row[colMap['지급 기간']]);
        const extra_benefits = escapeSql(row[colMap['추가 혜택']]);
        const target_description = escapeSql(row[colMap['선발 대상']]);
        const eligibility = escapeSql(row[colMap['신청 자격']]);
        const selection_count = escapeSql(row[colMap['선발 인원']]);
        const application_period = escapeSql(row[colMap['접수 기간']]);
        const application_end = parseDate(row[colMap['마감 기한']]);
        const application_method = escapeSql(row[colMap['접수 방법']]);
        const required_documents = escapeSql(row[colMap['제출 서류']]);
        const contact = escapeSql(row[colMap['문의처']]);
        const application_link = escapeSql(row[colMap['url']]);

        // Matching Criteria
        const target_grade = escapeSql(row[colMap['대상학년']] || '1,2,3,4');
        const min_gpa = row[colMap['최소학점']] || 0;
        const max_income = row[colMap['최대소득']] || 10;
        const target_gender = escapeSql(row[colMap['성별']] || 'any');
        const target_school_type = escapeSql(row[colMap['대학종류']] || 'university,college,grad_school,cyber,open');
        const target_region = escapeSql(row[colMap['학생거주지역']] || '전국');
        const target_major_category = escapeSql(row[colMap['전공계열']] || '무관');
        const min_prev_semester_credits = row[colMap['직전이수학점']] || 0;
        const special_criteria = row[colMap['특화자격']] ? `'{${row[colMap['특화자격']]}'}` : 'NULL'; // Array format? No, text array in Postgres uses {a,b}
        // Actually special_criteria is text[] in DB. 
        // If excel has "multicultural, farmer", we need to format as '{multicultural,farmer}'
        let special_criteria_val = 'NULL';
        if (row[colMap['특화자격']]) {
            const tags = String(row[colMap['특화자격']]).split(',').map(s => s.trim());
            special_criteria_val = `'{"${tags.join('","')}"}'`; // Postgres array literal
        }

        const target_nationality = escapeSql(row[colMap['국적']] || 'Korea');
        const target_parents_region = escapeSql(row[colMap['부모거주지역']] || '전국');
        const target_university_region = escapeSql(row[colMap['대학교 지역']] || '전국');
        const target_high_school_region = escapeSql(row[colMap['고등학교지역']] || '전국');
        const max_csat_grade = row[colMap['수능']] || 9;
        const max_school_grade = row[colMap['내신']] || 9;

        const enrollmentRaw = row[colMap['재학상태']];
        const target_enrollment_status = mapEnrollment(enrollmentRaw);

        sql += `INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            ${name}, ${foundation}, ${category}, ${amount}, ${support_details}, ${benefit_type},
            ${payment_method}, ${payment_period}, ${extra_benefits}, ${target_description},
            ${eligibility}, ${selection_count}, ${application_period}, ${application_end},
            ${application_method}, ${required_documents}, ${contact}, ${application_link},
            ${target_grade}, ${min_gpa}, ${max_income}, ${target_gender}, ${target_school_type},
            ${target_region}, ${target_major_category}, ${min_prev_semester_credits},
            ${special_criteria_val}, ${target_nationality}, ${target_parents_region},
            ${target_university_region}, ${target_high_school_region}, ${max_csat_grade},
            ${max_school_grade}, ${target_enrollment_status}
        );\n`;
    });

    fs.writeFileSync(OUTPUT_FILE, sql);
    console.log(`Successfully generated SQL to ${OUTPUT_FILE}`);
}

run();
