-- Generated by convert_excel_to_sql.js
TRUNCATE TABLE scholarships;

INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '앨트웰민초장학재단 제26기 장학생', '앨트웰민초 장학재단', 'private', '등록금 전액 + 월 40만원 또는 월 70만원', '(택1) 1. 등록금+면학보조금(6개월) / 2. 면학보조금만(6개월)', '복합지원',
            '등록금 대납 + 현금 지급', '차년도 1학기부터 총 6개 학기 지급', '없음', '9월 현재 국내 4년제 대학교 1학년 2학기에 재학 중인 자',
            '계절학기 제외 총 15학점 이상 이수하고, 평점 A(4.0/4.5만점, 3.7/4.3만점) 이상인 자 & 공직, 언론, 연구 및 기타 전문직 진출 희망자(의료계열 제외)', '30명', '2025-09-01 ~ 2025-09-26', '2025-09-26',
            '우편 접수 + 지원정보 입력 시 서류 전형 → 면접 심사', '지원서, 자기소개서, 대학교 성적증명서 원본, 수능 성적증명서(수시의 경우 고등학교 성적증명서 가능), 학자금 지원구간 통지서(당해년도 최신화분, 한국장학재단 홈페이지 발급)', '앨트웰민초장학재단 사무국 (02-508-2168)', 'https://www.mincho.or.kr/',
            '1', 4, 10, 'any', 'university',
            '전국', '무관', 15,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2025 제28기 두을장학생', '두을장학재단', 'private', '등록금 전액 + 90만원', '학기당 지급(자기계발비), 워크샵 및 커뮤니티 활동 지원 포함', '복합지원',
            '등록금 대납 + 현금 지급', '2학년~졸업 시까지', '두을장학생 커뮤니티 활동 지원(동문멘토링, 듀얼멘토링, 홈커밍데이, 독서모임 등)', '두을장학재단의 인재상에 공감하며, 차세대 여성지도자가 되기를 희망하는 대한민국 국적의 여학생',
            '당해년도 2학기 기준 국내 4년제 대학교 1학년 2학기 재학생(사이버대학/방송통신대학 제외)이자 정규 1학기 총 15학점 이상을 이수하고, 성적이 3.5/4.5 이상 취득한 자', '30명', '2025-09-01 ~ 2025-09-30', '2025-09-30',
            '홈페이지 → 온라인 지원서 작성 및 서류 pdf 업로드', '대학교 재학증명서/성적증명서, 가족관계증명서 또는 등본, 학자금 지원구간 통지서(한국장학재단 발급), 그 외 해당자에 한 해 추가서류 있음', '두을장학재단 선발위원회 (02-3287-6377)', 'https://www.dooeul.or.kr/web/main.do',
            '1', 3.5, 10, 'female', 'university',
            '전국', '무관', 15,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            'STX장학재단 2026 장학생', 'STX장학재단', 'private', '등록금(300만원 한도) + 월 50만원', '연간 최대 1,200만원, 학업보조금 지원', '복합지원',
            '등록금 대납 + 현금 지급', '최대 2년 (조기 졸업 시 지원 종료)', '없음', '국내 국공립, 사립 종합 4년제 대학교 3학년 1학기(5학기) 진급예정자 (4학기 재학생 혹은 4학기 이수한 복학예정자)',
            '2학년 1학기까지 평점평균 B+ (3.3/4.3 또는 3.5/4.5) 이상(3학년 1학기 복학예정자는 2학년 2학기까지)', '20명', '2025-10-31 ~ 2025-11-14', '2025-11-14',
            '온라인 접수 → 서류 심사 (12월) → 면접 심사 (1월)', '주민등록등본, 성적증명서(전 학년 수강내역), 인턴/대외활동/봉사활동 증명서, 당해 2학기 기준 학자금지원구간통지서, 재학/휴학증명서', '재단법인 STX장학재단 사무국 (02-2271-9351)', 'http://www.stxfoundation.or.kr/index/',
            '2', 3.5, 10, 'any', 'university',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2026년 두산연강 대학 장학생', '두산연강재단', 'private', '400만원', '학기당 지급', '생활비',
            '현금 지급', '졸업 시까지', '워크샵 및 소모임', '국내 대학교 중 4년제 학과에 소속된 대한민국 국적의 학부생',
            '1. 2026년 3월(1학기) 기준, 2학년 1학기 진학 예정자\n2. 선발 후 2026년 1학기, 2학기 모두 재학이 가능한 자\n3. 전체 학기 성적 평점 평균이 3.0/4.5 이상인 자(공고일 현재 1학년 2학기에 재학 중인 경우에는 1학년 1학기 성적으로 지원)\n4. 한국장학재단 소득분위(2025년 2학기 기준) 6분위 이내인 자(군 복무, 휴학 등으로 2025년 2학기 소득분위가 없을 경우 대체 서류 제출)\n5. 수여식 등 재단에서 주최하는 행사에 참석이 가능한 자 ※ 2026년 2월 예정인 장학증서 수여식 불참 시 장학생 선발이 취소됨', '00명', '2025-10-15 ~ 2025-11-14', '2025-11-14',
            '서류 전형 → 면접 전형 → 합격자 발표', '1. (재단 양식) 추천서 : 소속 학과 학과장 또는 지도교수 작성 및 날인 \n2. 재학(휴학) 증명서 \n3. 성적 증명서 \n4. 가족관계증명서(부 또는 모 기준 ‘상세’로 발급) \n5. 소득분위서류(2025년 2학기 한국장학재단 학자금 지원구간 통지서) \n(군 복무, 휴학 등으로 2025년 2학기 소득분위가 없을 경우 아래 대체 서류 제출) \n* 대체 서류(1, 2, 3 모두 하나의 PDF파일로 스캔하여 제출) \n1) 부모님 건강보험료(직장, 지역) 납부 확인서 (최근 12개월 기준) \n2) 부모님 지방세 세목별 과세증명서(2025년) \n3) 부모님 근로소득 원천징수 영수증(2024년) 또는 소득금액증명원(2024년) \n6. 가계곤란 증빙서류(수급자 증명서, 차상위계층 확인서 또는 차상위본인부담경감증명서, 한부모가족증명서, 장애수당(장애인연금) 대상자 확인서 등 해당자만 제출)', '두산연강재단 학술장학팀 장학담당자 (02-708-5514)', 'https://www.yonkang.org/kr/support/information/?id=96',
            '1', 3, 6, 'any', 'university',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2025 신규 협성장학생 - 부울경 고교 출신 전형', '협성문화재단', 'private', '등록금 + 50만원', '학기당 지급, 생활비 지원', '복합지원',
            '등록금 대납 + 현금 지급', '4학년 2학기까지 (단, 신입생은 당해년도 2학기부터)', '인문학 강의, 마음사랑 캠프, 해외 탐방 프로그램, 해외 봉사활동 지원 자격 및 가산점 부여', '부산·울산·경남지역의 고등학교 출신의 국내 4년제 대학교 신입생 또는 2~3학년 재학생',
            '부산지역 내 4년제 이상 대학교의 신입생 (수능 평균 4등급 이내) 또는 2~3학년 재학생인 자 (직전학기 12학점 이상 이수, 평점 3.2/4.5 또는 3.0/4.3 이상인 자). 저소득층 가정 또는 보육시설 및 그룹홈에서 성장한 학생 우선 지원', '20~30명', '2024-12-16 ~ 2025-01-06', '2025-01-06',
            '협성문화재단 접수 → 서류심사 → 면접심사 → 최종합격', '지원서, 자기소개서, 추천서, 가족관계증명서, 건강보험 자격확인서, 건강보험료 납부확인서, 소득금액증명원, 퇴직공제금 적립내역서, 재학증명서, 성적증명서 등', '협성문화재단 상담 (051-503-0341)', 'http://hscf.co.kr/kor/sub6_01.php',
            '1', 0, 10, 'any', 'university',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '부산', '부산,울산,경남', 4,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2025 신규 협성장학생 - 부울경 고교 출신 전형', '협성문화재단', 'private', '등록금 + 50만원', '학기당 지급, 생활비 지원', '복합지원',
            '등록금 대납 + 현금 지급', '4학년 2학기까지 (단, 신입생은 당해년도 2학기부터)', '인문학 강의, 마음사랑 캠프, 해외 탐방 프로그램, 해외 봉사활동 지원 자격 및 가산점 부여', '부산·울산·경남지역의 고등학교 출신의 국내 4년제 대학교 신입생 또는 2~3학년 재학생',
            '부산지역 내 4년제 이상 대학교의 신입생 (수능 평균 4등급 이내) 또는 2~3학년 재학생인 자 (직전학기 12학점 이상 이수, 평점 3.2/4.5 또는 3.0/4.3 이상인 자). 저소득층 가정 또는 보육시설 및 그룹홈에서 성장한 학생 우선 지원', '20~30명', '2024-12-16 ~ 2025-01-06', '2025-01-06',
            '협성문화재단 접수 → 서류심사 → 면접심사 → 최종합격', '지원서, 자기소개서, 추천서, 가족관계증명서, 건강보험 자격확인서, 건강보험료 납부확인서, 소득금액증명원, 퇴직공제금 적립내역서, 재학증명서, 성적증명서 등', '협성문화재단 상담 (051-503-0341)', 'http://hscf.co.kr/kor/sub6_01.php',
            '2,3', 3.2, 10, 'any', 'university',
            '전국', '무관', 12,
            NULL, 'Korea', '전국',
            '전국', '부산,울산,경남', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2025 신규 협성장학생 - 건설근로자 자녀 전형', '협성문화재단', 'private', '등록금 + 50만원', '학기당 지급, 생활비 지원', '복합지원',
            '등록금 대납 + 현금 지급', '4학년 2학기까지 (단, 신입생은 당해년도 2학기부터)', '인문학 강의, 마음사랑 캠프, 해외 탐방 프로그램, 해외 봉사활동 지원 자격 및 가산점 부여', '건설근로자공제회 기준 총 적립일수 756일 이상이면서 2024년도 근로내역이 100일 이상 적립된 피공제자의 자녀로, 국내 4년제 이상 대학교의 신입생 또는 2~3학년 재학생',
            '부산지역 내 4년제 이상 대학교의 신입생 (수능 평균 4등급 이내) 또는 2~3학년 재학생인 자 (직전학기 12학점 이상 이수, 평점 3.2/4.5 또는 3.0/4.3 이상인 자)', '20명', '2024-12-16 ~ 2025-01-06', '2025-01-06',
            '협성문화재단 접수 → 서류심사 → 면접심사 → 최종합격', '지원서, 자기소개서, 추천서, 가족관계증명서, 건강보험 자격확인서, 건강보험료 납부확인서, 소득금액증명원, 퇴직공제금 적립내역서, 재학증명서, 성적증명서 등', '협성문화재단 상담 (051-503-0341)', 'http://hscf.co.kr/kor/sub6_01.php',
            '1', 0, 10, 'any', 'university',
            '전국', '무관', 0,
            '{"construction"}', 'Korea', '전국',
            '부산', '전국', 4,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '2025 신규 협성장학생 - 건설근로자 자녀 전형', '협성문화재단', 'private', '등록금 + 50만원', '학기당 지급, 생활비 지원', '복합지원',
            '등록금 대납 + 현금 지급', '4학년 2학기까지 (단, 신입생은 당해년도 2학기부터)', '인문학 강의, 마음사랑 캠프, 해외 탐방 프로그램, 해외 봉사활동 지원 자격 및 가산점 부여', '건설근로자공제회 기준 총 적립일수 756일 이상이면서 2024년도 근로내역이 100일 이상 적립된 피공제자의 자녀로, 국내 4년제 이상 대학교의 신입생 또는 2~3학년 재학생',
            '부산지역 내 4년제 이상 대학교의 신입생 (수능 평균 4등급 이내) 또는 2~3학년 재학생인 자 (직전학기 12학점 이상 이수, 평점 3.2/4.5 또는 3.0/4.3 이상인 자)', '20명', '2024-12-16 ~ 2025-01-06', '2025-01-06',
            '협성문화재단 접수 → 서류심사 → 면접심사 → 최종합격', '지원서, 자기소개서, 추천서, 가족관계증명서, 건강보험 자격확인서, 건강보험료 납부확인서, 소득금액증명원, 퇴직공제금 적립내역서, 재학증명서, 성적증명서 등', '협성문화재단 상담 (051-503-0341)', 'http://hscf.co.kr/kor/sub6_01.php',
            '2,3', 3.2, 10, 'any', 'university',
            '전국', '무관', 12,
            '{"construction"}', 'Korea', '전국',
            '부산', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            'KRX국민행복재단 (홈페이지 확인 불가)', 'KRX국민행복재단', 'private', '150만원', '학기당 지급, 생활비 지원', '생활비',
            '현금 지급', '별도 확인 필요', '없음', '부산소재 4년제 및 전문 대학교에 재학 중인 2~4학년생',
            '기초생활수급자, 법정차상위계층 및 소득구간 1~3구간. 직전 정규학기 12학점 이상 이수 및 全학기 성적 백분위 70점 이상', '별도 확인 필요', '11월', NULL,
            NULL, NULL, '(02-3774-8821)', NULL,
            '2,3,4', 2, 3, 'any', 'university,college',
            '전국', '무관', 12,
            '{"basic_livelihood","second_lowest"}', 'Korea', '전국',
            '부산', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '포스코한국유학장학', '포스코청암재단', 'private', '등록금 전액 + 월 100만원 + 정착금 100만원', '- 석사과정: 4학기 등록금 전액과 생활비 22개월 (100만원/월)\n- 박사/석박사통합과정: 6학기 등록금 전액과 생활비 36개월 (100만원/월)\n- 초기 정착금 100만원(1회), 국민건강보험료(NHIS) 등', '복합지원',
            NULL, '학위 과정 별 상이', '한국어 교육 지원, 증서수여식, 페어웰, 한국 문화체험 지원', '아시아 국적 소유자로 차년도 석·박사과정에 진학하고자 하는 자',
            '① 학사 학위 취득(예정자) 중 외국 국적을 소유한 자 (한국/이중국적 불가)\n② 협력 대학원의 석사 또는 박사과정(석·박 통합과정 포함) 입학허가를 받은 자 중 소속 대학원으로부터 추천을 받은 자', '20명', '5월', NULL,
            '대학원 입학 허가 → 대학원 추천 접수 → 재단심사(면접)', NULL, '\n02-562-0227 / \nasiafellowship@postf.org', 'https://www.postf.org/asia/abroad/business',
            '1', 0, 10, 'any', 'grad_school',
            '전국', '무관', 0,
            NULL, 'Asian', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '글로벌우수대학장학', '포스코청암재단', 'private', NULL, NULL, '복합지원',
            NULL, NULL, '교육세미나, 포스코주니어리더펠로십 참여기회, 오리엔테이션, \n펠로간 커뮤니티 활동', '외국인 유학생',
            '외국인 유학생', '10개국 20개 대학 240명', '7월', NULL,
            'MOU 체결/갱신 → 모집공고 → 선발 → 증서수여 → 장학금 송금 → 오리엔테이션 → 커뮤니티 활동', NULL, '02-562-4950 / asia_univ@postf.org', 'https://www.postf.org/asia/local/business',
            '1,2,3,4', 0, 10, 'any', 'university,college,grad_school,cyber,open',
            '전국', '무관', 0,
            NULL, 'Foreigner', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '한국전공대학원생펠로십', '한국국제교류재단', 'private', NULL, NULL, NULL,
            NULL, NULL, NULL, '외국인 유학생',
            '외국인 유학생', NULL, NULL, NULL,
            NULL, NULL, 'yrjeong@kf.or.kr', NULL,
            '1,2,3,4', 0, 10, 'any', 'university,college,grad_school,cyber,open',
            '전국', '무관', 0,
            NULL, 'Foreigner', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '글로벌 장학 프로그램, GSP', '대웅재단', 'private', '월 50만원', '학기 중 50만원/월 지급 (방학 기간 제외)', '복합지원',
            NULL, NULL, '1. 학기 중 실제 회사 프로젝트 참여\n2. 방학 중 직장 체험 및 인턴십 참여\n3. 취업 추천 및 추천서 발급', '1. 현재 국내 대학에 재학 중인 외국인 대학(원)생\n2. 한국어 혹은 영어로 의사소통이 가능한 학생',
            '1. 본인 진로나 소개에 대해 논리적이고 구체적으로 설명할 수 있는 학생\n2. 재단 프로그램에 열정적으로 참여하여 성장하고자 하는 의지가 있는 학생\n3. 졸업 후 한국 혹은 본국 취업 희망하는 학생', NULL, '상시', '2025-09-22',
            '모집 공고 → 지원서 접수 → 평가 (서류/면접) → 선발', '지원서 (양식 지정), 과제 동영상, 재학증명서, 성적증명서 등', 'df@daewoong.co.kr', 'http://daewoongfoundation.or.kr/Board/Board.asp?ModuleID=1&PageSize=10&Key=T&Keyword=%EA%B8%80%EB%A1%9C%EB%B2%8C&sCategory=&sIsNotice=&Page=1&Mode=V&IDX=253',
            '1,2,3,4', 0, 10, 'any', 'university,college,grad_school',
            '전국', '무관', 0,
            NULL, 'Foreigner', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '신진의과학자 학술연구지원', '대웅재단', 'private', '최대 5,000만원', '석사(22개월)/박사(36개월) 생활비 지원, 건보료 등 포함', NULL,
            NULL, '1년 (2025년 12월 ~ 2026년 11월)', NULL, NULL,
            '만 45세 미만 MD, VMD, RPH, PHD 취득자', NULL, '45880', '2025-09-12',
            NULL, NULL, NULL, 'http://daewoongfoundation.or.kr/Board/Board.asp?ModuleID=1&PageSize=10&Key=&Keyword=&sCategory=&sIsNotice=&Page=1&Mode=V&IDX=375',
            '1,2,3,4', 0, 10, 'any', 'grad_school',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '통합운동전문인재 장학프로그램', '대웅재단', 'private', '최대 150만원 (월 50만원)', '학기 중 지급 (방학 기간 제외)', '지원금',
            NULL, NULL, '마스터 트레이너 지도 교육, 국내 10대 기업 근골격계 센터 견학 기회, 수료자 대상 힐리언스 코어운동센터 트레이너 채용 우대', '운동을 통한 건강 개선에 관심이 있고, 프로그램의 목표와 취지에 부합하는 학생\n\n개인적인 성장 가능성과 발전 의지가 확인되는 학생\n\n운동 관련 전문 분야 진출 및 취업을 희망하는 학생\n\n운동 관련 자격증 보유자 우대',
            '체육대학 소속 학생\n\n물리치료과 학생\n\n운동 관련 건강 향상 목적을 두고 공부하는 학생\n\n비전공자이지만 운동·건강 산업 분야에 관심이 있는 학생도 지원 가능', NULL, NULL, '2025-09-21',
            NULL, NULL, NULL, 'http://daewoongfoundation.or.kr/Board/Board.asp?ModuleID=1&PageSize=10&Key=&Keyword=&sCategory=&sIsNotice=&Page=1&Mode=V&IDX=378',
            '1,2,3,4', 0, 10, 'any', 'university,college,grad_school,cyber,open',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '말 전문인재 장학프로그램', '대웅재단', 'private', '최대 250만', '비과세, 간접비 포함', NULL,
            NULL, NULL, NULL, '말 산업 관련 전공학생\n\n전문 교육기관 또는 특성화 학과 재학생\n\n말과 승마 산업 분야 진로 희망자\n\n전공이 아니더라도 말 산업에 열정이 있는 학생 포함',
            '1. 말 산업 교육기관 및 말 특성화 학과(고등학교/대학교) 소속 학생\n2. 말 관련 전공(말산업학과, 말 사업학과, 승마학과, 승마관련학과)\n3. 비전공자라도 말 산업에 관심 있는 학생이라면 지원 가능', '0명', NULL, '2025-09-10',
            NULL, NULL, NULL, 'http://daewoongfoundation.or.kr/Board/Board.asp?ModuleID=1&PageSize=10&Key=&Keyword=&sCategory=&sIsNotice=&Page=1&Mode=V&IDX=376',
            '1,2,3,4', 0, 10, 'any', 'university,college',
            '전국', '무관', 0,
            NULL, 'Korea', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
INSERT INTO scholarships (
            name, foundation, category, amount, support_details, benefit_type, 
            payment_method, payment_period, extra_benefits, target_description, 
            eligibility, selection_count, application_period, application_end, 
            application_method, required_documents, contact, link,
            target_grade, min_gpa, max_income, target_gender, target_school_type,
            target_region, target_major_category, min_prev_semester_credits,
            special_criteria, target_nationality, target_parents_region,
            target_university_region, target_high_school_region, max_csat_grade,
            max_school_grade, target_enrollment_status
        ) VALUES (
            '농업분야 학술지원사업', '대웅재단', 'private', '학기 중 50만원/월 지급 (방학 기간 제외)', '월 분할 지급', NULL,
            NULL, NULL, NULL, '농업 관련 연구자\n\n농업 분야 연구를 수행하고자 하는 연구자(국적 무관)',
            '1. 농업 관련 박사학위(Ph.D) 소지자\n2. 국내외 대학, 대학 부설 연구소, 공공 연구기관 소속 연구자\n3. 관련 연구 실적 보유자 우대', NULL, '45870', '2025-08-17',
            NULL, NULL, NULL, 'http://daewoongfoundation.or.kr/Board/Board.asp?ModuleID=1&PageSize=10&Key=&Keyword=&sCategory=&sIsNotice=&Page=1&Mode=V&IDX=266',
            '1,2,3,4', 0, 10, 'any', 'university,grad_school',
            '전국', '자연', 0,
            NULL, 'Any', '전국',
            '전국', '전국', 9,
            9, 'enrolled,leave,expected'
        );
